name: Apply Template Labels
on:
  workflow_dispatch: # run manually after repo creation

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Sync labels from template repo
        uses: r7kamura/github-label-sync-action@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repository: monark-community/repo-structure-template
          source_path: .github/labels.yml
          allow_added_labels: "true" # keeps existing extra labels